name: AI PR Review
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

concurrency:
  group: ai-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run AI PR Reviewer
        uses: Yeray-nm1/ai-pr-review@main
        with:
          groq_api_key: ${{ secrets.GROQ_API_KEY }}
          groq_model: llama-3.1-8b-instant
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
